it_keywords:
  # 프로그래밍 언어
  - 파이썬
  - 자바
  - JavaScript
  - TypeScript
  - C언어
  - C++
  - C#
  - Go언어
  - Rust
  - Swift
  - Kotlin
  - PHP
  - Ruby
  - SQL
  - R언어

  # 웹 개발
  - 프론트엔드
  - 백엔드
  - 풀스택
  - React
  - Vue.js
  - Angular
  - Node.js
  - Express
  - Django
  - Spring
  - SpringBoot
  - REST API
  - GraphQL
  - 웹서버
  - 마이크로서비스
  - Docker
  - 쿠버네티스
  - AWS
  - Azure
  - GCP

  # 데이터베이스
  - MySQL
  - PostgreSQL
  - MongoDB
  - Redis
  - Oracle
  - NoSQL
  - 데이터베이스
  - SQL튜닝
  - 인덱싱

  # 인공지능/머신러닝
  - 머신러닝
  - 딥러닝
  - TensorFlow
  - PyTorch
  - 데이터사이언스
  - 빅데이터
  - 인공지능
  - 강화학습
  - 자연어처리
  - NLP
  - 컴퓨터비전

  # 핵심 컴퓨터 과학
  - 알고리즘
  - 자료구조
  - 운영체제
  - 네트워크
  - 컴퓨터구조
  - 디자인패턴
  - 객체지향
  - 컴파일러

  # 개발 방법론/도구
  - Git/GitHub
  - 애자일
  - 스크럼
  - TDD
  - 클린코드
  - 리팩토링
  - DevOps
  - CI/CD
  - 유닛테스트
  - 디버깅
  - 코드리뷰

  # 모바일 개발
  - 안드로이드
  - iOS
  - Flutter
  - React Native
  - 크로스플랫폼

  # 보안
  - 정보보안
  - 암호화
  - OAuth
  - JWT
  - HTTPS
  - 보안취약점

  # 게임 개발
  - Unity
  - Unreal Engine
  - 게임서버

  # 최신 기술
  - 블록체인
  - 클라우드네이티브
  - 서버리스
  - WebAssembly
  - MSA

  # 개발자 필수
  - 기술면접
  - 코딩테스트
  - 시스템설계
  - 아키텍처패턴

  # 데이터 엔지니어링
  - ETL
  - 데이터파이프라인
  - 데이터웨어하우스
  - 데이터레이크
  - 데이터마이닝

  # 개발 문화/실천방법
  - 클린아키텍처
  - 소프트웨어설계
  - 코드품질
  - 성능최적화